"""posts table fix

Revision ID: 61149baed44b
Revises: 8eef31501a76
Create Date: 2020-08-06 19:18:12.774408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61149baed44b'
down_revision = '8eef31501a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
